name: ðŸš€ Deploy to Play Store
on:
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "alpha"
        type: choice
        options:
          - alpha
          - promote_to_production

jobs:
  fastlane-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ¤– Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter environnement
        uses: subosito/flutter-action@v2.7.1
        with:
          channel: 'master'

      - name: ðŸ”„ Get Application dependencies
        run: flutter pub get

      - name: ðŸ”‘ Set Rapid API Key
        run: |
          sed -i 's/\[GIVE ME AN API KEY\]/'"${RAPID_API_KEY}"'/g' lib/service/domaine_service.dart
        env:
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}

      - name:  Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: android

      - name: ðŸ” Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      - name: ðŸš€ Deploy to play store or ðŸ“² Promote to production
        run: bundle exec fastlane ${{ github.event.inputs.lane || 'alpha' }}
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android
