name: üöÄ Deploy to Play Store
on:
  release:
    types: [published]


jobs:
  fastlane-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ü§ñ Checkout Code
        uses: actions/checkout@v3

      - name: üõ† Setup Flutter environnement
        uses: subosito/flutter-action@v2.7.1
        with:
          channel: "master"

      - name: üîÑ Get Application dependencies
        run: flutter pub get

      - name: üîë Set Rapid API Key
        run: |
          sed -i 's/\[GIVE ME AN API KEY\]/'"${RAPID_API_KEY}"'/g' lib/service/domaine_service.dart
        env:
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}

      - name: üõ† Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: android

      - name: üîê Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      - name: üèó Build Android App Bundle (aab)
        run: flutter build appbundle

      - name: üß™ Deploy to closing test
        run: bundle exec fastlane alpha
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android
